### ISSUE TITLE
Constant max-old-size

### ISSUE THREAD

**Issue by Lwdthe1** [damianmr/heroku-node-settings#4]
Hey, I'm running my app on Heroku with a Procfile. I have the following in my procfile:

<img width="674" alt="screen shot 2018-08-11 at 10 59 13 pm" src="https://user-images.githubusercontent.com/5778798/43999103-3840ae6e-9dba-11e8-9749-6742882087fb.png">

Both of my web and worker processes are using Standard 2X dynos which have 1BG memory limit, but heroku-node-settings is setting their max-old-size to 256MB: 

<img width="884" alt="screen shot 2018-08-11 at 10 57 54 pm" src="https://user-images.githubusercontent.com/5778798/43999102-3827b148-9dba-11e8-80e1-53b3bad83c2e.png">

Is this the expected behavior?

P.S. thanks for making this, it has helped me greatly: https://github.com/nodejs/node/issues/3370#issuecomment-412316400

**Comment by nicovanbelle** [comment]
Doesn't seem right to me as it's taking the flags for a 512MB dyno

**Comment by cfey** [comment]
I have the same issue, is there a workaround for that?

**Comment by damianmr** [comment]
Hey guys, sorry for the late response! I wasn't receiving notifications for the repo. 

As far as I can tell, I can only wonder why is that Heroku reports such a value for the `WEB_MEMORY` variable. 

As per the official documentation in Heroku: https://devcenter.heroku.com/articles/node-concurrency#tuning-the-concurrency-level

> `WEB_MEMORY` specifies, in MB, the expected memory requirements of your application’s processes. It defaults to 512.

> `WEB_CONCURRENCY` specifies the recommended number of processes to cluster for your application. It’s essentially `MEMORY_AVAILABLE` / `WEB_MEMORY`.

So, probably is because Heroku doesn't change the default `WEB_MEMORY` value when you have better Dynos. If you don't plan to play with the concurrency settings in your app (read the link above), you could just set it yourself so you let the process know that it has all the juice available.

`heroku config:set WEB_MEMORY=1024 --app YOUR_APP_NAME`
